name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
   inputs:
      input:
        description: "Execute CI/CD"
        required: false
        default: "Execute CI/CD manually"

env:
  SOLUTION: ./DesafioCDB.sln
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code ⬇️
      uses: actions/checkout@v3

    - name: Setup .NET 8 🚧
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
         
    - name: Restore and Test CS 🏗️
      run: |
        dotnet restore ${{ env.SOLUTION }} 
          dotnet test ${{ env.SOLUTION }} 
     

